name: theming
description: A collection of theming related widgets and utilities using riverpod
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  intl: any
  json_annotation: ^4.8.1
  misc_utils:
    path: ../misc_utils
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  lint: ^2.1.2
  riverpod_generator: any
  riverpod_lint: any

flutter:
  uses-material-design: true
